### ISSUE TITLE
Buildbot should prioritize release builds vs. pr builds

### ISSUE THREAD

**Issue by delroth** [dolphin-emu/fifoci#11]
In order to avoid PRs being built before their parent.

In practice it's not too much of a problem, one run of manage.py fixup_data fixes that.

**Comment by Pokechu22** [comment]
I think this was implemented by dolphin-emu/sadm@407b698640febbc7ff67a638e266df931cee82e4 (your own commit, 5 days after this issue was filed), though I haven't actually checked if it works in practice.
