### ISSUE TITLE
FifoCI broken since 5.0-12891

### ISSUE THREAD

**Issue by Pokechu22** [dolphin-emu/fifoci#26]
FifoCI seems to be broken since 5.0-12891, or since https://github.com/dolphin-emu/dolphin/pull/9182.  FifoCI build 551 ([sw](https://dolphin.ci/#/builders/20/builds/551), [ogl](https://dolphin.ci/#/builders/14/builds/551)) worked fine, while 552 failed to generate any images, with messages like `ls: cannot access '/tmp/dolphin.446HbQhTNL/.dolphin-emu/Dump/Frames/*.png': No such file or directory` ([sw](https://dolphin.ci/#/builders/20/builds/552), [ogl](https://dolphin.ci/#/builders/14/builds/552)).  The problem seems to be due to an assumption that the generated AVI file name is `framedump0.avi`, while now it is e.g. `00000000_2020-10-23_18-12-35_0.avi`.  The relevant code is this:

https://github.com/dolphin-emu/fifoci/blob/9d2ba6dad90ed6c846165c4b51edd95eb6ac12cd/runner/linux/run_fifo_test.sh#L67-L78

It could probably be fixed by changing it to `$DUMPDIR/*.avi`, but that seems a bit jank.  Also, oddly, both sw and ogl create AVI files; the SW renderer path doesn't seem like it is being used.

-----

`fifoci-ogl-lin-radeon` also appears to be broken, but for some other reason (and from much further back); it can't find `ninja`.  Build [80](https://dolphin.ci/#/builders/8/builds/80) succeeded, build [81](https://dolphin.ci/#/builders/8/builds/81) failed.  Not sure what happened there.

**Comment by Pokechu22** [comment]
The main issue here is fixed; all that's left is the side-issue of `fifoci-ogl-lin-radeon` not working.  A current broken build, [636](https://dolphin.ci/#/builders/8/builds/636), shows

> ```
> CMake Error at CMakeLists.txt:13 (project):
>   Running
>
>    '/nix/store/yr04i7akn3j9qwhcfsz1ajd1rwqi25gl-ninja-1.9.0/bin/ninja' '--version'
>
>   failed with:
>
>    No such file or directory
> ```

and also shows `/nix/store/ba77flp1iya22w2v7yih1vwz8z4zwdnb-ninja-1.10.1/bin` and `/nix/store/ba77flp1iya22w2v7yih1vwz8z4zwdnb-ninja-1.10.1/sbin` in the `PATH`.

Build [80](https://dolphin.ci/#/builders/8/builds/80), which succeeded, had `/nix/store/i2xn0gms4wmv5mmvs5hw43mkmy5pzibx-ninja-1.9.0/bin` and `/nix/store/i2xn0gms4wmv5mmvs5hw43mkmy5pzibx-ninja-1.9.0/sbin` in the `PATH`.  Build [81](https://dolphin.ci/#/builders/8/builds/81), which failed, had the exact same ones in the `PATH`, but failed with this:

> ```
> CMake Error at CMakeLists.txt:13 (project):
>   Running
> 
>    '/nix/store/yr04i7akn3j9qwhcfsz1ajd1rwqi25gl-ninja-1.9.0/bin/ninja' '--version'
> 
>   failed with:
> 
>    No such file or directory
> ```

Note that both 81 and 636 attempt to use `yr04i7akn3j9qwhcfsz1ajd1rwqi25gl-ninja-1.9.0` even though the `PATH` has something different.  I don't know much about NixOS, so I'm not sure what the deal with that is.  I'm also not sure where the relevant configuration is (if there even is any).

**Comment by delroth** [comment]
This is cmake being stupid and requiring clean builds when the path to binaries changes. I could probably force builds from scratch on that builder, but it's annoying and expensive.

**Comment by Pokechu22** [comment]
Radeon builds were fixed by delroth/infra.delroth.net@7631148ad14ee248dda1f43f22352bc8bed8b791.  All fifoci instances are now working.
